### PR TITLE
Add postproc integration test

### PR DESCRIPTION
**Pull request by aethr**
## Description

Refactor postprocessing just enough to create an integration test to enshrine the current behaviour. This will be useful as we start to make changes to the results format, to ensure we haven't broken anything.

The idea of the refactor is to make `posterior_emissions_postprocess` (and `calculate_average_emissions` which it invokes) take all the parameters they need as arguments, instead of using global variables which contain things like the archive folder or emissions filename template. When it's invoked in the user_driver, we can source these from the global variables, but when we run this from a test we can pass test data instead.

## Checklist

Please confirm that this pull request has done the following:

- [x] Tests added
- [ ] Documentation added (where applicable)
- [x] Changelog item added to `changelog/`

### CODE REVIEW

**Comment by aethr** [comment]
@prayner I removed `get_posterior` and `find_last_iteration` from `calculate_average_emissions`, as this now takes the result from the minimiser as an input parameter.

If it's still important to be able to run `calculate_average_emissions` from an iteration file, I think this would be best achieved by a standalone script that can load the last iteration and pass it to `posterior_emissions_postprocess`. Let me know if you'd like me to add that.

**Comment by prayner** [comment]
I think your solution is fine. Just make sure we deal with the case where
the minimiser doesn't converge so there's no file equivalent to
the current "final_solution.ncf" and we're left dealing with the last
iter???.ncf file.

**Comment by aethr** [comment]
@prayner will `user_driver.post_process` be called in the scenario where the minimiser doesn't converge? Or would we be running the post proc manually in that case to evaluate the last iteration?

**Comment by prayner** [comment]
I do expect we would evaluate whether it's converged enough then run manually

**Comment by aethr** [comment]
I've added `scripts/manual_postproc.py` which can be invoked like:

```shell
poetry run python src/postproc/run_manual_postproc.py \
  --archive-dir /var/openmethane-e2e/monthly/aust-test/v1/2022-07-22/archive_Pert/202207_test_vsn1 \
  --template-dir /var/openmethane-e2e/monthly/aust-test/v1/2022-07-22/templates
```

This will:
- search for `<archive-dir>/posterior_multipliers.nc`, if not found, for `<archive-dir>/iter*.ncf`
- extract the emis/CH4 dataset and normalise down to 2 dimensions
- calculate the average emissions
- save the result in `<archive-dir>/posterior_emissions.nc`

**Comment by prayner** [comment]
In 39f04e5 why the os.path.join inside the pathlib.Path?

**Comment by aethr** [comment]
> In https://github.com/openmethane/openmethane/commit/39f04e56529a809a0e9a543dd7703b0a2798f39f why the os.path.join inside the pathlib.Path?

It's not necessary, and I think I refactored that after our recent conversation. Good catch.

**Review by prayner — APPROVED** [review]

**Comment by aethr** [comment]
I do find I'm getting slightly different results in this branch, but I believe it's simply due to having a higher precision, for example:

First row for a monthly run on `main` branch for 2022-07-22:
```
1.177412e-10,
8.209493e-11,
8.162522e-11,
8.508913e-11,
8.781233e-11,
```

First row for the same monthly run on this branch:
``` 
1.17741134197218e-10,
8.20949223840044e-11,
8.16252195768554e-11,
8.50891293375119e-11,
8.78123340192914e-11,
```

The rounding does look a bit odd, but the numbers look very similar. My guess would be that this is because this branch reworks the postproc to use the result in memory (PhysicalData) instead of reading it from the NetCDF file of the same.

@prayner let me know if you see any issues with this.

**Comment by prayner** [comment]
Yep, I'd call them equal ... which is why doing equality tests on
floating point is such a pain.

**Pull request merged**
